#!/usr/bin/expect
# Script to execute any command on the target m/c
# MACH-Machine name
# PASSWD-Machine password
# USER-User used to connect to the machine
# OPERATION-Any command eg  mkdir,rmdir etc
# LOGLEVEL-Specifies the level that is used when logging messages from sshd
# PORT-On which port the connection is being made

 set MACH [lindex $argv 0]
 set PASSWD [lindex $argv 1]
 set USER [lindex $argv 2]
 set OPERATION [lindex $argv 3]
 set timeout [lindex $argv 4]
 set rndm_token [lindex $argv 5]
 set LOGLEVEL [lindex $argv 6]
 set PORT [lindex $argv 7]
 if {$timeout > 0} {
    set timeout_seconds [expr {$timeout / 1000 + 10}]
 } else {
    set timeout_seconds 10
 }
 spawn ssh -o StrictHostKeyChecking=no -o ConnectTimeout=$timeout_seconds -o LogLevel=$LOGLEVEL -p 22 $USER@$MACH $OPERATION >/tmp/stderr.$rndm_token
 expect {
 "*assword*" {
             send "$PASSWD\r"
             expect eof
             }
 "*]*" {
        expect eof
       }
   }
catch wait result
exit [lindex $result 3]
